[package]
name = "shardio"
version = "0.4.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[features]
default = ['lz4']
# Switch on the 'full-test' feature (in release mode), to enable 
# some long-running stress-tests
full-test = []

[dependencies]
serde = "*"
serde_derive = "*"
bincode = ">=1.0"
byteorder = "*"
libc = "*"
flate2 = "*"
lz4 = { version = "*", optional = true }
rayon = "*"
crossbeam-channel = "0.1.2"
failure = "0.1.5"
failure_derive = "*"
pretty_assertions = "0.5.1"
min-max-heap = "1.0.2"

[dev-dependencies]
tempfile = "*"
criterion = "0.2.3"
fxhash = "*"
lazy_static = "*"

[[bench]]
name = "my_bench"
harness = false