[package]
name = "shardio"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
bincode = "0.8.0"
byteorder = "*"
libc = "*"
lz4 = "*"

[dev-dependencies]
tempfile = "*"
